name: Extract scripts and mod file and upload

on:
  workflow_call:
    inputs:
      nexusmods_mod_id:
        required: true
        type: string
      mod_version:
        required: false
        type: string
        default: ''
      mod_description:
        required: false
        type: string
        default: ''
      checkout_ref:
        required: true
        type: string
    secrets:
      NEXUSMODS_APIKEY:
        required: true
      NEXUSMODS_SESSION_COOKIE:
        required: true

jobs:
  pack-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Make Directory
        run: mkdir src
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}
          path: './src'
      - name: Repack zipball to be inside mod folder
        id: mod-repack
        run: |
          MODNAME=$(ls -1 ./src/*.mod | xargs -n 1 basename | sed s/.mod//)
          mkdir out
          mkdir out/${MODNAME}
          mv ./src/scripts ./out/${MODNAME}
          mv ./src/${MODNAME}.mod ./out/${MODNAME}
          echo "modname=${MODNAME}" >> "$GITHUB_OUTPUT"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.mod-repack.outputs.modname }}
          path: ./out/
    outputs:
      mod_name: ${{ steps.mod-repack.outputs.modname }}
  upload-release:
    needs: ["pack-mod"]
    uses: BUTR/workflows/.github/workflows/release-nexusmods.yml@master
    with:
      nexusmods_game_id: warhammer40kdarktide
      nexusmods_mod_id: ${{ inputs.nexusmods_mod_id }}
      mod_filename: ${{ needs.pack-mod.outputs.mod_name }}.zip
      mod_version: ${{ inputs.mod_version }}
      mod_description: ${{ inputs.mod_description }}
      artifact_name: ${{ needs.pack-mod.outputs.mod_name }}
    secrets:
      NEXUSMODS_APIKEY: ${{ secrets.NEXUSMODS_APIKEY }}
      NEXUSMODS_SESSION_COOKIE: ${{ secrets.NEXUSMODS_SESSION_COOKIE }}
